#!/usr/bin/expect
set timeout 360

spawn ./node_modules/.bin/vue init ../ test-project

# This happens because of
# https://github.com/vuejs/vue-cli/issues/291
expect "name" { send "\n" }
expect "author" { send "\n" }
